### ISSUE TITLE
Real Time graph error

### ISSUE THREAD

**Issue by Domotrique** [Domotrique/okovision_2023#1]
From ARK32 on [Okovision forum](https://forums.futura-sciences.com/logiciel-software-open-source/705908-okovision-retours-utilisateurs-37.html) 
J'ai une erreur dans le menu "Temps réel", je me demande si ca ne vient pas de php8.2 :

`[Tue Nov 14 16:02:53.556364 2023] [php:error] [pid 17] [client 10.8.0.1:47804] PHP Fatal error: Uncaught TypeError: Unsupported operand types: string * string in /var/www/html/_include/realTime.class.php:160\nStack trace:\n#0 /var/www/html/ajax.php(299): realTime->getdata()\n#1 {main}\n thrown in /var/www/html/_include/realTime.class.php on line 160`

J'obtiens cette erreur dans le menu "Temps réel" puis "Graphiques/Eau chaude", ca marche bien pour le graph Chaudière bizarrement, as-tu le même comportement Domotrique ?

**Comment by arkpoah** [comment]
t'as été plus rapide que moi :)
Pour info je viens de tester en php 7.4.33 et je n'ai plus l'erreur.

**Comment by Domotrique** [comment]
Hello, il est bien possible qu'il y ait une coquille...

Si je comprends bien, il y a un de tes graphs de la page d'accueil qui ne marche pas en temps réel.
Tu peux m'indiquer quelles valeurs tu as ajouté dans ce graph stp ? Parceque chez moi mes graphs fonctionnent bien en temps réel.

**Comment by arkpoah** [comment]
En effet c'est personnalisé ces graphs..
Voici les valeurs conernées par le graph qui a l'erreur :
![image](https://github.com/Domotrique/okovision_2023/assets/24526760/f87e66fc-f0b3-4546-9375-e678adcfb8fe)

**Comment by Domotrique** [comment]
Merci je regarde ça de suite !

**Comment by Domotrique** [comment]
Ha mais t'as l'ECS, moi je n'ai que le chauffage, du coup ce sont dex valeurs que je ne peux pas tester. T'as moyen de me montrer un graph de la page d'accueil avec les valeurs visibles stp ?
Il semblerait qu'une des valeurs soit interprétée en tant que texte au lieu de nombre.

**Comment by arkpoah** [comment]
Alors je ne suis pas sûr de ce que tu veux voir, mais voilà ce que ca donne sur la page d'accueil : 
![image](https://github.com/Domotrique/okovision_2023/assets/24526760/dd90031e-362e-4cc8-9c53-79dcaa4fcf25)

Et en base de données c'est sous cette forme : 
`
MariaDB [okovision]> select * from oko_historique_full limit 20;
+------------+----------+------------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+---------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| jour       | heure    | timestamp  | col_2 | col_3 | col_4 | col_5 | col_6 | col_7 | col_8 | col_9  | col_10 | col_11 | col_12 | col_13 | col_14 | col_15 | col_16  | col_17 | col_18 | col_19 | col_20 | col_21 | col_22 | col_23 | col_24 | col_25 | col_26 | col_27 | col_28 | col_29 | col_30 | col_31 | col_32 | col_33 | col_34 | col_35 | col_36 | col_37 | col_38 | col_39 | col_40 | col_41 | col_42 | col_43 | col_44 | col_45 | col_46 | col_47 | col_48 | col_49 | col_50 | col_51 | col_52 | col_53 | col_54 | col_55 |
+------------+----------+------------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+---------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+
| 2020-11-27 | 00:03:00 | 1606435380 |  8.20 |  8.30 |  0.00 | 42.90 | 42.10 |  0.00 | 19.00 | 100.00 |  -1.00 |  16.00 |  59.30 |  59.30 |  42.00 |   0.00 | 8200.00 |  48.70 |  47.10 |  23.00 |  58.00 | 582.50 | 701.90 | 745.00 |  26.63 |  80.00 |   0.00 |  41.00 |  69.10 |  69.00 |   0.00 |   0.00 |   4.00 |   0.00 |   0.00 |   0.00 |   0.00 |   0.00 |   1.00 |   0.00 |   0.00 |   0.00 |   0.00 |   0.00 |  42.90 |  59.30 |   1.00 |   0.00 |   0.00 | 180.00 |   1.00 |   0.00 |   0.00 |   0.00 |   0.00 |   1.00 |
| 2020-11-27 | 00:04:00 | 1606435440 |  8.20 |  8.30 |  0.00 | 43.00 | 42.10 |  0.00 | 19.00 | 100.00 |   0.00 |  16.00 |  59.30 |  59.30 |  42.00 |   0.00 | 8200.00 |  49.40 |  47.10 |  23.00 |  54.00 | 602.70 | 707.40 | 735.00 |  25.84 |  80.00 |   0.00 |  41.00 |  68.20 |  68.00 |   0.00 |   0.00 |   4.00 |   1.00 |   0.00 |   0.00 |   0.00 |   0.00 |   1.00 |   0.00 |   0.00 |   0.00 |   0.00 |   0.00 |  43.00 |  59.30 |   1.00 |   0.00 |   0.00 | 180.00 |   1.00 |   0.00 |   0.00 |   0.00 |   0.00 |   NULL |
| 2020-11-27 | 00:05:00 | 1606435500 |  8.20 |  8.30 |  0.00 | 43.10 | 42.10 |  0.00 | 19.00 | 100.00 |  -1.00 |  16.00 |  59.20 |  59.20 |  42.00 |   0.00 | 8200.00 |  50.00 |  47.10 |  23.00 |  50.00 | 612.10 | 711.40 | 720.00 |  28.54 |  80.00 |   0.00 |  42.00 |  69.70 |  70.00 |   0.00 |   0.00 |   4.00 |   0.00 |   0.00 |   1.00 |   0.00 |   0.00 |   1.00 |   0.00 |   0.00 |   0.00 |   0.00 |   0.00 |  43.20 |  59.20 |   1.00 |   0.00 |   0.00 | 180.00 |   0.00 |   0.00 |   0.00 |   0.00 |   0.00 |   NULL |
`

**Comment by Domotrique** [comment]
Tiens, essaye de mettre ce fichier à jour sur ton install, voir si ça corrige le soucis : https://github.com/Domotrique/okovision_2023/blob/Fix_Real_time_bug/_include/realTime.class.php

D'après tes données je ne vois pas de soucis, cela semble vraiment venir du temps réel.

**Comment by arkpoah** [comment]
Je te confirme que ça fonctionne maintenant, merci !

**Comment by Domotrique** [comment]
Cool, c'était donc un soucis de conversion de valeur. J'envoie ça dans le master !
