### ISSUE TITLE
Probleme mise à jour 1.12.2

### ISSUE THREAD

**Issue by Domotrique** [Domotrique/okovision_2023#12]
### Discussed in https://github.com/Domotrique/okovision_2023/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **Jelogofr** February  8, 2024</sup>
Bonjour Domotrique,

     je viens de réaliser la mise à jour via Okovision. Et dans la page d’accueil, je n'ai plus les valeurs de conso et de température. Elles sont toutes à 0 et j'ai ce message d'erreur en rouge "Problème de communication : rendu.getIndicByDay"

Que dois je faire pour faire régler le problème?

En te remerciant, et félicitation pour avoir réussi à mettre la fonction backup.
</div>

**Comment by Jelogofr** [comment]
@Domotrique 

Dois je toujours renommer le fichier comme tu me l'as indiqué avant?
