### ISSUE TITLE
Releases page

### ISSUE THREAD

**Issue by arkpoah** [Domotrique/okovision_2023#3]
Hello,

Pour info les dernières releases apparaissent uniquement en tag et non pas en release dans la page [Releases](https://github.com/Domotrique/okovision_2023/releases) comme c'était le cas pour les 1ères.
Je ne sais pas si c'est volontaire ou non.

Merci pour ces update en tout cas !

**Comment by Domotrique** [comment]
Salut,

Oui j'ai remarqué ça aussi, mais je ne comprends pas pourquoi.

Cela apparait bien sur la page d'accueil dans "last release", mais pas dans la liste des releases, juste dans les tags...

J'essaye de trouver ce que j'ai loupé.

**Comment by Domotrique** [comment]
Hello, J'ai trouvé le soucis, j'avais utilisé des tags interdits (avec 4 digits au lieu  de 3 max).
J'ai supprimé les tags en, question et tout est revenu dans l'ordre ! :)
