### ISSUE TITLE
L'utilisation de l'API ne semble pas fonctionner

### ISSUE THREAD

**Issue by Domotrique** [Domotrique/okovision_2023#4]
Message de Jelogo sur le forum :
J'essaie de récupérer des infos via le token API comme sur l'ancienne version d'okovision. Mais il me dit qu' apitoken est invalid. Pourtant j'ai pris celui indiqué dans la page "A propos", mais cela ne fonctionne pas.
Je met un exemple de demande basic comme indiqué dans la doc en mettant mon API: [http://okovision/api.php?token=0886f...eFromChaudiere](http://okovision/api.php?token=0886fdde9826&type=admin&action=getFileFromChaudiere)
et il me répond cette ligne là: {"response": false,"apiToken": "invalid"}
Aurais tu une idée?

**Comment by Domotrique** [comment]
Je viens de tester  et cela fonctionne bien chez moi.
Tu peux réessayer @Jelogo stp ?

**Comment by Domotrique** [comment]
Je suis aussi en 1.12.1.
En tapant cette adresse j'ai bien une réponse : 
`http://192.168.68.112/api.php?token=46591172362b&type=admin&action=getFileFromChaudiere`
IP de mon serveur = 192.168.68.112
mon token trouvé sur la page à propos : 46591172362b

Revérifie ton token peut-etre, sinon je ne vois pas...

**Comment by Jelogofr** [comment]
C'est bon ça marche!  je faisais une mauvaise manip
Merci beaucoup et bonne fin d'après midi
